### ISSUE TITLE
av2 get_data_info() return None during inference

### ISSUE THREAD

**Issue by xiazhongyv** [megvii-research/Far3D#10]
同 #7 和 #9，我使用您提供的create_av2_info文件生成100ms间隔的av2数据索引后，在验证集中仍存在cam_info为None的帧，这会导致在测试时get_data_info()的返回值为None并引发后续报错。想请教下您是如何解决这个问题的。

**Comment by xiazhongyv** [comment]
哦，我发现了自己理解的有问题，我把图像同步阈值理解成了帧间隔。
图像同步阈值应该是指loader.get_closest_cam_channel_timestamp中的匹配阈值，在#9中我的处理还是按照25ms的间隔处理的。
如果要修改这个阈值，我应该直接修改[av2.utils.synchronization_database.py Line 100 ](https://github.com/argoverse/av2-api/blob/main/src/av2/utils/synchronization_database.py#L100)，对吗？

**Comment by xiazhongyv** [comment]
问题已解决

**Comment by Amireux52** [comment]
老师您好，请问老师您是怎么修改的，我修改后仍然还是25ms,盼复

**Comment by Amireux52** [comment]
老师，可以告知下详细的修改结果吗，感激，盼复，祝好呢

**Comment by xiazhongyv** [comment]
> 老师，可以告知下详细的修改结果吗，感激，盼复，祝好呢

直接修改SynchronizationDB类对应实例的属性值（tools/create_infos_av2/create_av2_infos.py L45 的loader.MAX_LIDAR_RING_CAM_TIMESTAMP_DIFF）就可以了，或者直接去改site packages里av2-toolkit对应的代码也行。

不过我这里直接使用这个repo的代码，一直复现不出来论文中的结果...... 所以后来也没在用这个baseline.
如果您复现成功了欢迎@我一下~

**Comment by chenxinhe1** [comment]
好的呢，老师。
老师，您遇到过这个问题吗：https://github.com/megvii-research/Far3D/issues/28
如果可以，烦请告知下如何解决这个问题，感谢您，盼复

**Comment by Amireux52** [comment]
> > 老师，可以告知下详细的修改结果吗，感激，盼复，祝好呢
> 
> 直接修改SynchronizationDB类对应实例的属性值（tools/create_infos_av2/create_av2_infos.py L45 的loader.MAX_LIDAR_RING_CAM_TIMESTAMP_DIFF）就可以了，或者直接去改site packages里av2-toolkit对应的代码也行。
> 
> 不过我这里直接使用这个repo的代码，一直复现不出来论文中的结果...... 所以后来也没在用这个baseline. 如果您复现成功了欢迎@我一下~
好的呢，老师。
老师，您遇到过这个问题吗：https://github.com/megvii-research/Far3D/issues/28
如果可以，烦请告知下如何解决这个问题，感谢您，盼复

**Comment by Amireux52** [comment]
老师，可以发给我一份av2_train_infos.pkl文件吗，我的无法生成，谢谢拉
