### ISSUE TITLE
About NuScenes

### ISSUE THREAD

**Issue by Mollylulu** [megvii-research/Far3D#11]
Thanks for your great work and open source!
Can not find the nuscenes config in the repo. Could you please share it with me? Your assistance is much appreciated! You can reach me via email: wluo007@ntu.edu.sg

**Comment by xhjiang-pixel** [comment]
您好，config已发到您邮箱。

**Comment by xhjiang-pixel** [comment]
The config has been sent.

**Comment by Mollylulu** [comment]
Many thanks!

**Comment by Slonna** [comment]
hi ,can you share with me the nuscenes config? many thanks! email : <slonna119@gmail.com>

**Comment by vehxianfish** [comment]
Hello, could you please send a nuscense config file? Thank you. email:s_xu@foxmail.com.
@Mollylulu

**Comment by Yuning-Shi** [comment]
@Mollylulu @vehxianfish @Slonna @xhjiang-pixel 
Hello, could you please send a nuscense config file? Thank you so much. My email : 19ru601@ms.dendai.ac.jp

**Comment by imurfutur3** [comment]
@Mollylulu @vehxianfish @Slonna 
hi, could you share a copy with me? my email: cool4961@me.com
Thanks a lot!!!!
