### ISSUE TITLE
NuScenes Config

### ISSUE THREAD

**Issue by WestShellJia** [megvii-research/Far3D#12]
Thanks for your great work and open source!
Can I have a reference config for NuScenes data (jwestshell@gmail.com)? 
Thanks!

**Comment by xhjiang-pixel** [comment]
The config has been sent.

**Comment by SPA-junghokim** [comment]
Thank you for your great research and share your work!
Could i also receive nuScenes config?? (junghokim@spa.hanyang.ac.kr)
Thanks

**Comment by fengdian8564** [comment]
Thank you for your great research and share your work!
Could you please send the nuScenes config to me too? (fengdian8564@126.com))
Thanks for your help!

**Comment by BarathwajAnandan** [comment]
Awesome work breaking down the Farther prediction problem! I would really appreciate if I can get the config too :) Thanks
- [banandan@alumni.cmu.edu](url)

**Comment by designerZhou** [comment]
Thanks for your great work! May i have a reference config for NuScenes data  (jimwenqiang@163.com)?
Thanks!

**Comment by designerZhou** [comment]
> Thanks for your great work and open source! Can I have a reference config for NuScenes data ([jwestshell@gmail.com](mailto:jwestshell@gmail.com))? Thanks!

if you convinence,can you share a copy with me ?  (mailto:jimwenqiang@163.com)

**Comment by steven9046** [comment]
Thank you for your great research and share your work!
Could you please send the nuScenes config to me too? (chsun@ambarella.com)
Thanks!!!

**Comment by steven9046** [comment]
> Thanks for your great work and open source! Can I have a reference config for NuScenes data ([jwestshell@gmail.com](mailto:jwestshell@gmail.com))? Thanks!

Could you share a copy with me?(chsun@ambarella.com) 
Thanks a lot!

**Comment by xhjiang-pixel** [comment]
Sorry for the late reply.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "megvii-research/Far3D"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月12日(星期五) 下午5:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [megvii-research/Far3D] NuScenes Config (Issue #12)





  
Thanks for your great work and open source! Can I have a reference config for NuScenes data ***@***.***)? Thanks!
  
Could you share a copy with ***@***.***)
 Thanks a lot!

**Comment by shenyingying** [comment]
> The config has been sent.

can you send me a config,my email is shen222ying@163.com,thanks a lot

**Comment by WangzcBruce** [comment]
Hello! Have you got the config? Could you share with me? [wangzhechao21@mails.ucas.ac.cn](mailto:wangzhechao21@mails.ucas.ac.cn)

**Comment by vehxianfish** [comment]
Hello, could you please send a nuscense config file? Thank you. email:s_xu@foxmail.com.
@shenyingying @steven9046

**Comment by HIT-ShuWei** [comment]
> > Thanks for your great work and open source! Can I have a reference config for NuScenes data ([jwestshell@gmail.com](mailto:jwestshell@gmail.com))? Thanks!
> 
> Could you share a copy with me?([chsun@ambarella.com](mailto:chsun@ambarella.com)) Thanks a lot!

hi, have you recieved config? If so, could you share the config with me by email? 873195345@qq.com, thanks a lot!

**Comment by thomas-enxuli** [comment]
Thanks for the great work! Would you mind sharing the nuscenes config with me via email? tli@cs.toronto.edu Thanks!

**Comment by Zoe-Wan** [comment]
Thank you for the great work! Would you mind sharing the NuScenes config with me via email at [zoewan235711@gmail.com](zoewan235711@gmail.com)? Thanks！

**Comment by imurfutur3** [comment]
@shenyingying @designerZhou @Zoe-Wan @fengdian8564 @vehxianfish 
hi, could you share a copy with me? my email: cool4961@me.com
Thanks a lot!!!!

**Comment by Kevin-Matrix** [comment]
> Thanks for your great work and open source! Can I have a reference config for NuScenes data ([jwestshell@gmail.com](mailto:jwestshell@gmail.com))? Thanks!
@WestShellJia Hi! Could you please share a copy of NuScenes config with me?([604842168@qq.com](mailto:604842168@qq.com))
Thank you very much!

**Comment by ddsaplus** [comment]
> 配置已发送。

您好，请问能否分享一份给我的配置吗，非常感谢，我的邮箱：[cuiforwork@hnu.edu.cn](mailto:cuiforwork@hnu.edu.cn)

**Comment by weizf0606** [comment]
Thanks for your great work ! Could you share a copy of nuscenes config with  me? My email: [weixiaolingfeng@qq.com](url)
Thanks a lot !

**Comment by admyxs** [comment]
@WestShellJia @xhjiang-pixel  Hi! Thanks for sharing the great work. Could you please share the nuscenes config file with me. Thank you so much! My email is lide2591@163.com

**Comment by cx4711** [comment]
hi, have you recieved config? If so, could you share the config with me by email? [2910653559@qq.com](mailto:2910653559@qq.com), thanks a lot!

**Comment by cx4711** [comment]
> The config has been sent.
Thanks for your great work and open source!
Can I have a reference config for NuScenes data ([2910653559@qq.com](mailto:2910653559@qq.com))?
Thanks!
