### ISSUE TITLE
About Nuscenes Config

### ISSUE THREAD

**Issue by fengdian8564** [megvii-research/Far3D#13]
Thanks for sharing your work, it's excellent research.
Additionally, I was wondering if it would be possible for me to request a config of the Nuscenes data for reference? 
I'm looking forward to your response.

**Comment by WangzcBruce** [comment]
Hello! Have you got the config? Could you share with me? wangzhechao21@mails.ucas.ac.cn

**Comment by imurfutur3** [comment]
> Hello! Have you got the config? Could you share with me? [wangzhechao21@mails.ucas.ac.cn](mailto:wangzhechao21@mails.ucas.ac.cn)

hi, could you share a copy with me? my email: cool4961@me.com
Thanks a lot!!!!

**Comment by ddsaplus** [comment]
你好，请问能分享一份给我nuscenes的配置吗，非常感谢，我的邮箱：cuiforwork@hnu.edu.cn

**Comment by admyxs** [comment]
Hi! Thanks for sharing the great work. Could you please share the nuscenes config file with me. Thank you so much! My email is lide2591@163.com

**Comment by 670160532lileilei-wq** [comment]
670160532@qq.com  Could you please share the nuscenes config file with me. Thank you so much!
