### ISSUE TITLE
Would you share one pretrained model for evaluation usage?

### ISSUE THREAD

**Issue by fengye1966** [megvii-research/Far3D#2]
Thank you for opening source of this great work. Do you mind to share one of your pretrained model for eval usage which could go with the config file provided?  Thanks

**Comment by xhjiang-pixel** [comment]
Sorry for the late reply. If you still need the pretrained model ,please send an email to xhjiang@bit.edu.cn.

**Comment by xhjiang-pixel** [comment]
Sorry for the late reply. We update the weights and log at [result](https://github.com/megvii-research/Far3D?tab=readme-ov-file#results-on-argoverse-2-val-set).
