### ISSUE TITLE
about algoverse2 pkl  and eval problem

### ISSUE THREAD

**Issue by wengdunfang** [megvii-research/Far3D#26]
I have used your code (python tools/create_infos_av2/create_av2_infos.py) to generate av2_val_infos_mini.pkl. However, I noticed that several cameras are empty, such as 
'ring_front_left': None, 
'ring_front_center': None, 
'ring_rear_right': None 
in 'scene_id': '02678d04-cc9f-3148-9f95-1ba66347dff9'. 
Could you please provide me with a genuine pkl file? Thank you.

**Comment by wengdunfang** [comment]
If I use the pkl generated by me for inference, there is an error: 

bash tools/dist_test.sh projects/configs/far3d.py  /mnt/far3d/iter_82548.pth 4 --eval bbox
```
File "/mnt/Far3D/projects/mmdet3d_plugin/datasets/argoverse2-dataset_t. py", line 250, in __ getitem__
Return self. prepare_test_data (idx)
File "/mnt/Far3D/projects/mmdet3d_plugin/datasets/argoverse2_dataset_t. py", line 132, in preparetest_data
Self. pre pipeline (input-dict)
File "/mnt/Far3D/mmdetection3d/mmdet3d/datasets/custom3d. py", line 206, in pre pipeline
Results ['img_fields']=[]
TypeError: 'NoneType' object does not support item assignment
```
This is because some cameras are empty.
https://github.com/megvii-research/Far3D/blob/5efb9d73a246c39fac79b3cf8c20a8e059611c3f/projects/mmdet3d_plugin/datasets/argoverse2_dataset_t.py#L193C1-L194C1

**Comment by exiawsh** [comment]
@wengdunfang Hi, sorry for late response.
You can refer to this issue https://github.com/megvii-research/Far3D/issues/7#issuecomment-1862329081
enlarge the interval 
https://github.com/argoverse/av2-api/blob/main/src/av2/utils/synchronization_database.py#L100
![image](https://github.com/megvii-research/Far3D/assets/74858581/63de0892-44c9-4153-86f9-31aa3d5b05ea)

**Comment by Amireux52** [comment]
> @wengdunfang Hi, sorry for late response. You can refer to this issue [#7 (comment)](https://github.com/megvii-research/Far3D/issues/7#issuecomment-1862329081) enlarge the interval https://github.com/argoverse/av2-api/blob/main/src/av2/utils/synchronization_database.py#L100 ![image](https://private-user-images.githubusercontent.com/74858581/328102745-63de0892-44c9-4153-86f9-31aa3d5b05ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxOTAzOTYsIm5iZiI6MTcxODE5MDA5NiwicGF0aCI6Ii83NDg1ODU4MS8zMjgxMDI3NDUtNjNkZTA4OTItNDRjOS00MTUzLTg2ZjktMzFhYTNkNWIwNWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDExMDEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4YzBjMzVjZDU4YjVmZWViMzBlMTYyOTA2ZmIwZTI3MjY2NjMyMmI2MTc1NDg2ZWZiMGVmNzA2ZDdjMGRkNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sHtMCXnspBhcXIncg1WhoGj6uJFDYZCxm_ScRF-zPro)

老师，请问应该怎样修改呢，我没有修改成功，烦请指导，感激，盼复
