### ISSUE TITLE
ins_depthmap in NuScenes loader

### ISSUE THREAD

**Issue by esghif** [megvii-research/Far3D#3]
I tried training Far3d on NuScenes.

It fails on the line 
`gt_ins_depth = [img_meta['ins_depthmap'] for img_meta in img_metas]`
due to missing `ins_depthmap`.

Any hints how I can get that with NuScenes?

Thank you!

**Comment by xhjiang-pixel** [comment]
We construct the ins_depthmap in class "AV2DownsampleQuantizeInstanceDepthmap" in custom_pipeline.py. If you want to get that with NuScenes, the class should also be used.
