### ISSUE TITLE
Have you used query histories (i.e., model works on a video as StreamPETR) in your results?

### ISSUE THREAD

**Issue by lisanu** [megvii-research/Far3D#31]
Thank you for your excellent work. 

In your paper, you reported that StreamPETR achieved a 20.3 mAP on the Argoverse dataset, while Far3D reached a 24.5 mAP. These are good results for camera only networks - as they are close to CenterPoint's performance (27.4 mAP). 

I have a question regarding your testing process: For StreamPETR, did you enable the feature to maintain the history of object queries (i.e., StreamPETR's video feature), or did you only consider queries from a single frame? Also for Far3D, did you maintain the history of queries from the video?

I am asking this because I see that the queue size is set to 1 on your config file [here](https://github.com/megvii-research/Far3D/blob/5efb9d73a246c39fac79b3cf8c20a8e059611c3f/projects/configs/far3d.py#L28). My understanding was that the queue_size is the size of the sliding window (number of frames you pick from a video).

**Comment by helloworld77** [comment]
Query histories of StreamPETR are different from BEVFormer(BEV histories, load multi frame at one time), they are used by memory_len, trained by frame sequence, and thus form the memory of history.
