### ISSUE TITLE
Request for dataloader

### ISSUE THREAD

**Issue by myteen2** [megvii-research/Far3D#4]
Hello 
First of all, thank you for sharing the great work.

I've noticed that the code used the nori2 package to construct dataloader. The nori2 package fetches data from Amazon S3. 

I believe there might be another code snippet that handles dataloading from local storages without using nori2 package. 
If that is the case, could you kindly make that code available?
Thank you for your consideration 🙏

**Comment by xhjiang-pixel** [comment]
Sorry for the late reply. The local-storage version is updated.
