### ISSUE TITLE
get_data_info() cannot output None during inference.

### ISSUE THREAD

**Issue by synsin0** [megvii-research/Far3D#7]
I observe that some frames do not have all cameras synchronized during inference stage. And the validation fails if get_test_data() returns None. How to evaluate the whole frames for 23547 validation set?

**Comment by xhjiang-pixel** [comment]
We enlarge the threshold of cameras synchronizing to 100ms when creating data info, which is set as 25ms by AV2 official.

**Comment by Amireux52** [comment]
> We enlarge the threshold of cameras synchronizing to 100ms when creating data info, which is set as 25ms by AV2 official.

老师，请问您是如何修改的呢，可以告知下修改后的样子吗，我没有修改成功，盼复，感谢您
