### ISSUE TITLE
关于nuscenes

### ISSUE THREAD

**Issue by fengguibinyn** [megvii-research/Far3D#8]
感谢您开源，期待好久了，日后会提供nuscenes训练的config吗 或者方便发我一份吗 我的邮箱是guibin.feng00@gmail.com

**Comment by xhjiang-pixel** [comment]
您好，config已发到您邮箱。

**Comment by fengguibinyn** [comment]
感谢

**Comment by roymerry** [comment]
同求一份 nuscenes训练的config 谢谢 wangrui0217@outlook.com

**Comment by vehxianfish** [comment]
> 您好，config已发到您邮箱。

@xhjiang-pixel @fengguibinyn 
您好，感谢您的开源，能否发送一份nuscenes的config？ 感谢！s_xu@foxmail.com

**Comment by Yuning-Shi** [comment]
@xhjiang-pixel @fengguibinyn @roymerry @vehxianfish 
您好，可以分享一份nuscenes的config文件吗，非常感谢！ email : 19ru601@ms.dendai.ac.jp

**Comment by ddsaplus** [comment]
您好，请问能否分享一份给我的配置吗，非常感谢，我的邮箱：[cuiforwork@hnu.edu.cn](mailto:cuiforwork@hnu.edu.cn)

**Comment by admyxs** [comment]
您好，可以分享一份配置给我吗？非常感谢，这是我的邮箱： lide2591@163.com

**Comment by snowindog** [comment]
您好，可以分享一份配置给我吗？非常感谢，这是我的邮箱： 1178964700@qq.com
