### ISSUE TITLE
About nuScenes

### ISSUE THREAD

**Issue by xiazhongyv** [megvii-research/Far3D#9]
Update

I have not kept the config file nor written down the author's email address. 

Please do not send me any more emails asking for it.

-------------------------------

感谢您杰出的工作！
想参考下您在nuscenes数据集上的config，不知是否可以分享，非常感谢！

以及我在生成argoverse 2 info文件时，会有数行如下关于数据集图像缺失的提示：
No corresponding ring image at 315969904359876000: 27.5 > 25.0 ms
No corresponding ring image at 315969904359876000: 40.1 > 25.0 ms
No corresponding ring image at 315969904359876000: 32.6 > 25.0 ms
No corresponding ring image at 315966060559935000: 27.5 > 25.0 ms
No corresponding ring image at 315969614859771000: 27.7 > 25.0 ms
No corresponding ring image at 315969614859771000: 32.7 > 25.0 ms
......
想请教下这个是av2数据集的正常现象吗？

**Comment by xhjiang-pixel** [comment]
1）config已发；2）是正常的，AV2官方设置的图像同步阈值是25ms，我们当时处理数据时扩大到了100ms，不过train集还是有缺少图片的情况，训练时会跳过这些样本。

**Comment by xiazhongyv** [comment]
非常感谢！
还有一个问题，当我把batchsize从1调到2时，会报错：
File "/home/xiazhongyu/bevperception/mmdet3d/models/dense_heads/farhead.py", line 816, in build_query2d_proposal          
raise NotImplementedError
您有遇到过这个情况吗？

**Comment by xhjiang-pixel** [comment]
抱歉，因为目前我们采用threshold_score去选取adaptive_query时还没有做多batch_size适配，如果采用topk方式采样的话可以应用多batch_size

**Comment by Yuning-Shi** [comment]
@xiazhongyv @xhjiang-pixel 
您好，可以分享一份训练nuscenes时使用的config文件吗，我的邮箱是 "19ru601@ms.dendai.ac.jp"。非常感谢！！！

**Comment by imurfutur3** [comment]
@xiazhongyv @Yuning-Shi 
hi, could you share a copy with me? cool4961@me.com
Thanks a lot!!!!

**Comment by RicePasteM** [comment]
Hi, could you share a copy with me? [HuZhangchi@mail.ustc.edu.cn](HuZhangchi@mail.ustc.edu.cn)
Thanks a lot!!!!

**Comment by RicePasteM** [comment]
> Hi, could you share a copy with me? [HuZhangchi@mail.ustc.edu.cn](HuZhangchi@mail.ustc.edu.cn) Thanks a lot!!!!
@xiazhongyv @xhjiang-pixel
